services:
  teacher-api:
    build:
      context: ./teacher_api
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: EHEI_DB
      DB_USER: root
      DB_PASSWORD: 12345678
    volumes:
      - ./teacher_api/src:/var/www/html

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: EHEI_DB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: